In [1]:
import pandas as pd

In [2]:
html = pd.read_html('https://en.wikipedia.org/wiki/List_of_Super_Bowl_champions')

In [3]:
championships = html[1][0:53]

In [7]:
championships.head()

,Game,Date/Season,Winning team,Score,Losing team,Venue,City,Attendance,Ref
0,I[n 2],"January 15, 1967 AFL/NFL","Green Bay Packersn(1, 1–0)",35–10,"Kansas City Chiefsa(1, 0–1)",Los Angeles Memorial Coliseum,"Los Angeles, California[n 3]",61946,[12][13]
1,II[n 2],"January 14, 1968 AFL/NFL","Green Bay Packersn(2, 2–0)",33–14,"Oakland Raidersa(1, 0–1)",Miami Orange Bowl,"Miami, Florida[n 4]",75546,[14][13]
2,III[n 2],"January 12, 1969 AFL/NFL","New York Jetsa(1, 1–0)",16–7,"Baltimore Coltsn(1, 0–1)",Miami Orange Bowl (2),"Miami, Florida (2)[n 4]",75389,[15][13]
3,IV[n 2],"January 11, 1970 AFL/NFL","Kansas City Chiefsa(2, 1–1)",23–7,"Minnesota Vikingsn(1, 0–1)",Tulane Stadium,"New Orleans, Louisiana",80562,[16][13]
4,V,"January 17, 1971 1970","Baltimore ColtsA(2, 1–1)",16–13,"Dallas CowboysN(1, 0–1)",Miami Orange Bowl (3),"Miami, Florida (3)[n 4]",79204,[17][13]

In [5]:
date_format = championships['Date/Season'].apply(lambda x: x[0:16])
championships.date = pd.to_datetime(date_format)
# date_column = pd.to_datetime(date_format)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

In [8]:
championships.head()

,Game,Date/Season,Winning team,Score,Losing team,Venue,City,Attendance,Ref
0,I[n 2],"January 15, 1967 AFL/NFL","Green Bay Packersn(1, 1–0)",35–10,"Kansas City Chiefsa(1, 0–1)",Los Angeles Memorial Coliseum,"Los Angeles, California[n 3]",61946,[12][13]
1,II[n 2],"January 14, 1968 AFL/NFL","Green Bay Packersn(2, 2–0)",33–14,"Oakland Raidersa(1, 0–1)",Miami Orange Bowl,"Miami, Florida[n 4]",75546,[14][13]
2,III[n 2],"January 12, 1969 AFL/NFL","New York Jetsa(1, 1–0)",16–7,"Baltimore Coltsn(1, 0–1)",Miami Orange Bowl (2),"Miami, Florida (2)[n 4]",75389,[15][13]
3,IV[n 2],"January 11, 1970 AFL/NFL","Kansas City Chiefsa(2, 1–1)",23–7,"Minnesota Vikingsn(1, 0–1)",Tulane Stadium,"New Orleans, Louisiana",80562,[16][13]
4,V,"January 17, 1971 1970","Baltimore ColtsA(2, 1–1)",16–13,"Dallas CowboysN(1, 0–1)",Miami Orange Bowl (3),"Miami, Florida (3)[n 4]",79204,[17][13]